### ISSUE TITLE
Can you find one color versions of the logos with no background (white)?  

### ISSUE THREAD

**Issue by BedirT** [eneskemalergin/eneskemalergin.github.io#4]
http://www.na.edu/images/about/officeofthepresident/seal2015grey.png This is the one for NAU, if you do this it will look more legit.

And try not to scale the images (width and height balance is really important).

You might also consider recoloring the parts:
- [x] Department of ... (... part)

**Comment by eneskemalergin** [comment]
What do you mean by re-coloring them, using the same color with titles, or selecting better colors?

**Comment by eneskemalergin** [comment]
@BedirT  What do you think about the link, hovered, checked link colors? I think something different could look good. I believe the blue and it's shades is drowning the links. Any ideas? Orange/Yellow or better?

**Comment by BedirT** [comment]
@eneskemalergin Orange would be good, but just try to make it fit to the bg, it should be shiny and visible at the same time

**Comment by BedirT** [comment]
@eneskemalergin I meant better colors

**Comment by BedirT** [comment]
And, the logos, should be without background. It is important, extension will be either .png or .gif, These wouldn't work .jpeg, .jpg ...

**Comment by BedirT** [comment]
![ss](https://user-images.githubusercontent.com/10860127/31311873-247f84ae-ab7b-11e7-8b62-75960eb8047e.png)
 like this

**Comment by eneskemalergin** [comment]
It was like that before, than I added background color :(

**Comment by BedirT** [comment]
@eneskemalergin but they have to be white (logos)

**Comment by eneskemalergin** [comment]
@BedirT  Also check the latest look, if you have anything to add :+1: https://eneskemalergin.github.io/

**Comment by eneskemalergin** [comment]
It's hard to find white logos you know for everywhere

**Comment by BedirT** [comment]
CHECK OUT SOME OF MY WORKS part, please change the pictures -OSSU is good- rest is trash ;)

**Comment by BedirT** [comment]
Like I said don't scale them :)

**Comment by BedirT** [comment]
https://www.google.com/search?q=harmony+public+schools+logo+white&client=safari&rls=en&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjEzLT5ud_WAhXQJlAKHRg-CgcQ_AUICigB&biw=1182&bih=812#imgrc=RXAEYmsn4_XIwM:

**Comment by eneskemalergin** [comment]
@BedirT  I am actually thinking to scrap that part completely

**Comment by BedirT** [comment]
http://www.oncocare.ca/logo_bcchri.png

**Comment by eneskemalergin** [comment]
@BedirT O zaman haciiiii, sen digerlerinide beyazlatsan vector halinde gonderde bari onlari koyayim

Gerci siz Hackathon dasiniz sanirim simdi

**Comment by BedirT** [comment]
Well done 👍
